### ISSUE TITLE
Can't see the Result file in eval.ai's my submissions

### ISSUE THREAD

**Issue by hiroking0523** [facebookresearch/hand_tracking_toolkit#6]
Thank you for hosting this competition.

I have a question about the problem on eval.ai.
Currently, in My Submissions on eval.ai, I cannot see the Result file. When I open it, it looks like this.
> "

On the leaderboard, I can see the result of the submission file with the highest score, but I cannot see the other files.
Can you please make it possible to see the other results as well?

Thank you in advance.

**Comment by lg-zhang** [comment]
Hi, thanks for reporting. It looks like this is a limitation of evalAI. The result file isn't working.
As a workaround, I'll just update the script to print the metrics such that you can see the results in the stdout file

**Comment by hiroking0523** [comment]
@lg-zhang 
Thanks for the reply.

I understood about the limitations of eval.ai, and I would appreciate it if you could let me know when you are able to see the scores in the stdout file.

Thank you very much.

**Comment by hiroking0523** [comment]
@lg-zhang 
Thank you for your response.
I was just able to check the score in the Stdout file in My Submmitons!

Please close this issue. Please keep us posted.
